spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eistore?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: ${spring.application.name}-pool
      minimum-idle: 10
      maximum-pool-size: 50
  redis:
    host: 172.31.205.27
    port: 6379
    password: REDIS1.t!@#
    database: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true